apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: "csb-producer"
  description: "CSB Rest producer"
  tags:
    - java
spec:
  type: service
  lifecycle: experimental
  owner: "group:default/backstage-admins"
  system: system:default/smongiar
  providesApis: 
    - csb-server-api