- restConfiguration:
    apiContextPath: /api-doc
    #bindingMode: json
    #bindingPackageScan: com.redhat.csbproducer.model

- rest:
    id: rest-openapi
    openApi:
      id: openapi-configuration
      specification: https://raw.githubusercontent.com/smongiar/smongiar-csb-server-api-api/main/specification.yaml
      missingOperation: ignore